### ISSUE TITLE
Leaving the emptiness dimension in new generated chunks into overworld results in server crash

### ISSUE THREAD

**Issue by Lumpous** [KELETU66666/ThaumicTinkerer#17]
Java on Server:
openjdk version "1.8.0_422"
OpenJDK Runtime Environment (build 1.8.0_422-8u422-b05-1~22.04-b05)
OpenJDK 64-Bit Server VM (build 25.422-b05, mixed mode)

thaumictinkerer-1.12.2-5.7.1-Unofficial.jar

---

When trying to leave the emptiness-dimension using a dimensional fracture, to return to the overworld, my server had some hard crashes.
Location to where i would have returned would have been in newly generated chunks.
Returning to the nether in an already generated chunk works without issues.

Solution was to edit NBT-data of my players file to a location where chunks had already been generated.

[crash-2024-10-11_13.57.20-server.txt](https://mclo.gs/VfEdr9S)
[crash-2024-10-11_13.33.28-server.txt](https://mclo.gs/XaXIgTB)
[crash-2024-10-11_13.27.03-server.txt](https://mclo.gs/wxRkzJ9)
[crash-2024-10-11_13.17.31-server.txt](https://mclo.gs/d272pmW)

---
https://github.com/xJon/The-1.12.2-Pack/issues/984

**Comment by KELETU66666** [comment]
may fixed, if not fix, pls reopen this issue

**Comment by xJon** [comment]
Appears to be fixed with the latest mod update 💯
