### ISSUE TITLE
Conflict between:  thaumisc-3.1.0+ - Alpha - 3,  thaumictinkerer-1.12.2-5.4.3-Unofficial, TConstruct-1.12.2-2.13.0.183

### ISSUE THREAD

**Issue by Fisher148** [KELETU66666/ThaumicTinkerer#4]
During the launch of Minecraft, a conflict occurs between three mods:

thaumisc-3.1.0+ - Alpha - 3 
thaumictinkerer-1.12.2-5.4.3-Unofficial
TConstruct-1.12.2-2.13.0.183

Minecraft crashes and gives the following error:
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumisc (keletupack)

**Comment by KELETU66666** [comment]
don't use thaumisc anymore
